list = []
a = int(input())
list.append(a)
b = int(input())
list.append(b)
c = int(input())
list.append(c)
d = int(input())
list.append(d)
e = int(input())
list.append(e)
f = int(input())
list.append(f)
g = int(input())
list.append(g)
h = int(input())
list.append(h)
i = int(input())
list.append(i)

print(max(list))
print(list.index(max(list)) + 1)